{% set name = "fps-resource-usage" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_resource_usage-{{ version }}.tar.gz
  sha256: 82bf9c057f257d71aff74474b911e8b89cebdca23f1ac926fb563efe690d933f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.7.0,<1
    - psutil >=5.9.4
    - types-psutil
    - anyio >=3.6.2,<5

test:
  requires:
    - python {{ python_min }}
  imports:
    - fps_resource_usage

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/resource_usage
  summary: An FPS plugin for the resource usage API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/resource_usage
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
