{% set name = "fps-resource-usage" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_resource_usage-{{ version }}.tar.gz
  sha256: c262095ee12e871afc15a17ad0aab278d2f1fc520af43f84d756367f87d2b4e9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - jupyverse-api >=0.1.4,<1
    - psutil >=5.9.4
    - types-psutil
    - anyio >=3.6.2

test:
  imports:
    - fps_resource_usage

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/resource_usage
  summary: An FPS plugin for the resource usage API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/resource_usage
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
