schema_version: 1

context:
  version: "0.10.1"

package:
  name: fps-resource-usage
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-resource-usage/fps_resource_usage-${{ version }}.tar.gz
    sha256: bb053122b4b10626959781383d520da925ee424b89b1240130deee3c53a26ec2

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.14.0,<0.15.0
    - psutil >=5.9.4
    - types-psutil

tests:
  - python:
      imports: fps_resource_usage
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/resource_usage
  summary: An FPS plugin for the resource usage API

extra:
  recipe-maintainers:
    - davidbrochart
